version: '3.8'
include:
  - supabase/docker/docker-compose.yml
services:
  express:
    container_name: express
    build: 
      context: ./waste-to-gold-backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_ACCESS_KEY_ID}
      - S3_BUCKET_NAME=${AWS_ACCESS_KEY_ID}
    depends_on:
      db:
        # Disable this if you are using an external Postgres database
        condition: service_healthy
